export interface ReportData {
  district: string;
  state: string;
  water_level_mbgl: number;
  soe_pct: number;
  gsi_score: number;
  status: string;
  ai_summary: string;
  recommendations: string[];
}

export function generateCGWBReportPDF(data: ReportData) {
  // Create a clean, printable HTML document window that triggers print / save to PDF
  const printWindow = window.open('', '_blank');
  if (!printWindow) return;

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <title>CGWB Official Groundwater Assessment Report - ${data.district}</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          margin: 40px;
          color: #1e293b;
          line-height: 1.6;
        }
        .header {
          text-align: center;
          border-bottom: 2px solid #0284c7;
          padding-bottom: 20px;
          margin-bottom: 30px;
        }
        .header img {
          height: 60px;
        }
        .title {
          font-size: 20px;
          font-weight: bold;
          color: #0f172a;
          margin-top: 10px;
          text-transform: uppercase;
        }
        .subtitle {
          font-size: 13px;
          color: #64748b;
        }
        .grid {
          display: grid;
          grid-template-columns: 1fr 1fr;
          gap: 20px;
          margin-bottom: 30px;
        }
        .card {
          background: #f8fafc;
          border: 1px solid #e2e8f0;
          padding: 15px;
          border-radius: 6px;
        }
        .card-title {
          font-size: 12px;
          font-weight: bold;
          color: #64748b;
          text-transform: uppercase;
        }
        .card-value {
          font-size: 22px;
          font-weight: bold;
          color: #0369a1;
          margin-top: 5px;
        }
        .badge {
          display: inline-block;
          padding: 4px 10px;
          font-size: 12px;
          font-weight: bold;
          border-radius: 4px;
          color: white;
        }
        .bg-critical { background-color: #ef4444; }
        .bg-warning { background-color: #f97316; }
        .bg-safe { background-color: #10b981; }
        .section {
          margin-bottom: 25px;
        }
        .section-title {
          font-size: 15px;
          font-weight: bold;
          color: #0f172a;
          border-bottom: 1px solid #cbd5e1;
          padding-bottom: 5px;
          margin-bottom: 10px;
        }
        ul {
          padding-left: 20px;
        }
        li {
          margin-bottom: 6px;
        }
        .footer {
          margin-top: 50px;
          border-top: 1px solid #e2e8f0;
          padding-top: 15px;
          text-align: justify;
          font-size: 10px;
          color: #94a3b8;
        }
      </style>
    </head>
    <body>
      <div class="header">
        <div class="subtitle">Central Ground Water Board (CGWB) & High-Resolution DWLR Analytics</div>
        <div class="title">District Groundwater Resource Assessment Profile</div>
        <div class="subtitle">Generated by AquaGround AI DSS • ${new Date().toLocaleDateString('en-IN', { dateStyle: 'full' })}</div>
      </div>

      <div class="grid">
        <div class="card">
          <div class="card-title">Target District & State</div>
          <div class="card-value">${data.district}, ${data.state}</div>
        </div>
        <div class="card">
          <div class="card-title">Groundwater Status</div>
          <div style="margin-top:5px;">
            <span class="badge ${data.status.includes('Critical') || data.status.includes('Exploited') ? 'bg-critical' : 'bg-safe'}">
              ${data.status}
            </span>
          </div>
        </div>
        <div class="card">
          <div class="card-title">DWLR Water Level (m bgl)</div>
          <div class="card-value">${data.water_level_mbgl} m bgl</div>
        </div>
        <div class="card">
          <div class="card-title">Groundwater Sustainability Index (GSI)</div>
          <div class="card-value">${data.gsi_score} / 100</div>
        </div>
      </div>

      <div class="section">
        <div class="section-title">AI Hydrogeological Assessment & Diagnostic Summary</div>
        <p>${data.ai_summary}</p>
      </div>

      <div class="section">
        <div class="section-title">Recommended Policy & Action Plan Interventions</div>
        <ul>
          ${data.recommendations.map(r => `<li>${r}</li>`).join('')}
        </ul>
      </div>

      <div class="footer">
        CONFIDENTIAL & OFFICIAL CGWB EVALUATION REPORT • AquaGround AI Decision Support System • Powered by DWLR Real-time Telemetry & Google Gemini XAI.
      </div>

      <script>
        window.onload = function() {
          window.print();
        }
      </script>
    </body>
    </html>
  `;

  printWindow.document.write(html);
  printWindow.document.close();
}
