// =============================================================================
// AquaGround AI — Mock Data
// Comprehensive realistic data for all entities
// =============================================================================

import type {
  District, Sensor, Alert, Prediction, AIRecommendation,
  DecisionRecord, Report, User, WaterLevelReading
} from '@/types';

// ── Helper ────────────────────────────────────────────────────────────────────
function daysAgo(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
}

function hoursAgo(n: number): string {
  const d = new Date();
  d.setHours(d.getHours() - n);
  return d.toISOString();
}

function generateWaterLevelHistory(base: number, count: number = 24): WaterLevelReading[] {
  return Array.from({ length: count }, (_, i) => {
    const variation = (Math.random() - 0.4) * 0.5;
    return {
      timestamp: daysAgo(count - i),
      depth: +(base + variation * i * 0.1).toFixed(2),
      extraction: +(Math.random() * 2 + 1).toFixed(2),
      recharge: +(Math.random() * 1.5 + 0.5).toFixed(2),
      rainfall: +(Math.random() * 15).toFixed(1),
    };
  });
}

// ── Districts ─────────────────────────────────────────────────────────────────
export const MOCK_DISTRICTS: District[] = [
  // ── NORTH INDIA ─────────────────────────────────────────────────────────────
  {
    id: 'dist-001',
    name: 'Jhansi',
    state: 'Uttar Pradesh',
    coordinates: { lat: 25.4484, lng: 78.5685 },
    healthScore: 28,
    riskLevel: 'critical',
    trend: 'down',
    rainfall: 412,
    groundwaterDepth: 34.2,
    extractionRate: 8.4,
    rechargeRate: 2.1,
    activeSensors: 12,
    offlineSensors: 3,
    totalSensors: 15,
    alerts: [],
    waterLevelHistory: generateWaterLevelHistory(34, 30),
    lastUpdated: hoursAgo(1),
  },
  {
    id: 'dist-002',
    name: 'New Delhi',
    state: 'Delhi (NCT)',
    coordinates: { lat: 28.6139, lng: 77.2090 },
    healthScore: 24,
    riskLevel: 'critical',
    trend: 'down',
    rainfall: 620,
    groundwaterDepth: 41.5,
    extractionRate: 14.2,
    rechargeRate: 2.8,
    activeSensors: 28,
    offlineSensors: 4,
    totalSensors: 32,
    alerts: [],
    waterLevelHistory: generateWaterLevelHistory(41, 30),
    lastUpdated: hoursAgo(0.5),
  },
  {
    id: 'dist-003',
    name: 'Kanpur',
    state: 'Uttar Pradesh',
    coordinates: { lat: 26.4499, lng: 80.3319 },
    healthScore: 35,
    riskLevel: 'high',
    trend: 'down',
    rainfall: 820,
    groundwaterDepth: 26.4,
    extractionRate: 9.6,
    rechargeRate: 3.4,
    activeSensors: 16,
    offlineSensors: 2,
    totalSensors: 18,
    alerts: [],
    waterLevelHistory: generateWaterLevelHistory(26, 30),
    lastUpdated: hoursAgo(2),
  },
  {
    id: 'dist-004',
    name: 'Ludhiana',
    state: 'Punjab',
    coordinates: { lat: 30.9010, lng: 75.8573 },
    healthScore: 38,
    riskLevel: 'high',
    trend: 'down',
    rainfall: 524,
    groundwaterDepth: 28.4,
    extractionRate: 12.3,
    rechargeRate: 4.1,
    activeSensors: 18,
    offlineSensors: 1,
    totalSensors: 19,
    alerts: [],
    waterLevelHistory: generateWaterLevelHistory(28, 30),
    lastUpdated: hoursAgo(0.5),
  },
  {
    id: 'dist-005',
    name: 'Amritsar',
    state: 'Punjab',
    coordinates: { lat: 31.6340, lng: 74.8723 },
    healthScore: 41,
    riskLevel: 'high',
    trend: 'down',
    rainfall: 598,
    groundwaterDepth: 22.1,
    extractionRate: 10.8,
    rechargeRate: 3.9,
    activeSensors: 16,
    offlineSensors: 0,
    totalSensors: 16,
    alerts: [],
    waterLevelHistory: generateWaterLevelHistory(22, 30),
    lastUpdated: hoursAgo(1),
  },
  {
    id: 'dist-006',
    name: 'Karnal',
    state: 'Haryana',
    coordinates: { lat: 29.6857, lng: 76.9905 },
    healthScore: 32,
    riskLevel: 'critical',
    trend: 'down',
    rainfall: 540,
    groundwaterDepth: 31.8,
    extractionRate: 11.5,
    rechargeRate: 2.9,
    activeSensors: 14,
    offlineSensors: 2,
    totalSensors: 16,
    alerts: [],
    waterLevelHistory: generateWaterLevelHistory(31, 30),
    lastUpdated: hoursAgo(1),
  },
  {
    id: 'dist-007',
    name: 'Agra',
    state: 'Uttar Pradesh',
    coordinates: { lat: 27.1767, lng: 78.0081 },
    healthScore: 36,
    riskLevel: 'high',
    trend: 'down',
    rainfall: 650,
    groundwaterDepth: 27.5,
    extractionRate: 9.1,
    rechargeRate: 3.2,
    activeSensors: 15,
    offlineSensors: 1,
    totalSensors: 16,
    alerts: [],
    waterLevelHistory: generateWaterLevelHistory(27, 30),
    lastUpdated: hoursAgo(2),
  },
  {
    id: 'dist-008',
    name: 'Dehradun',
    state: 'Uttarakhand',
    coordinates: { lat: 30.3165, lng: 78.0322 },
    healthScore: 72,
    riskLevel: 'low',
    trend: 'stable',
    rainfall: 1850,
    groundwaterDepth: 9.2,
    extractionRate: 4.1,
    rechargeRate: 8.5,
    activeSensors: 10,
    offlineSensors: 0,
    totalSensors: 10,
    alerts: [],
    waterLevelHistory: generateWaterLevelHistory(9, 30),
    lastUpdated: hoursAgo(3),
  },

  // ── WEST INDIA ─────────────────────────────────────────────────────────────
  {
    id: 'dist-009',
    name: 'Jaipur',
    state: 'Rajasthan',
    coordinates: { lat: 26.9124, lng: 75.7873 },
    healthScore: 39,
    riskLevel: 'high',
    trend: 'down',
    rainfall: 550,
    groundwaterDepth: 18.4,
    extractionRate: 7.9,
    rechargeRate: 3.5,
    activeSensors: 15,
    offlineSensors: 1,
    totalSensors: 16,
    alerts: [],
    waterLevelHistory: generateWaterLevelHistory(18, 30),
    lastUpdated: hoursAgo(1.5),
  },
  {
    id: 'dist-010',
    name: 'Bikaner',
    state: 'Rajasthan',
    coordinates: { lat: 28.0229, lng: 73.3119 },
    healthScore: 22,
    riskLevel: 'critical',
    trend: 'down',
    rainfall: 281,
    groundwaterDepth: 58.7,
    extractionRate: 11.2,
    rechargeRate: 1.3,
    activeSensors: 8,
    offlineSensors: 5,
    totalSensors: 13,
    alerts: [],
    waterLevelHistory: generateWaterLevelHistory(58, 30),
    lastUpdated: hoursAgo(2),
  },
  {
    id: 'dist-011',
    name: 'Jodhpur',
    state: 'Rajasthan',
    coordinates: { lat: 26.2389, lng: 73.0243 },
    healthScore: 31,
    riskLevel: 'critical',
    trend: 'down',
    rainfall: 310,
    groundwaterDepth: 47.3,
    extractionRate: 9.8,
    rechargeRate: 2.0,
    activeSensors: 14,
    offlineSensors: 2,
    totalSensors: 16,
    alerts: [],
    waterLevelHistory: generateWaterLevelHistory(47, 30),
    lastUpdated: hoursAgo(1),
  },
  {
    id: 'dist-012',
    name: 'Ahmedabad',
    state: 'Gujarat',
    coordinates: { lat: 23.0225, lng: 72.5714 },
    healthScore: 48,
    riskLevel: 'moderate',
    trend: 'stable',
    rainfall: 780,
    groundwaterDepth: 21.3,
    extractionRate: 7.2,
    rechargeRate: 4.8,
    activeSensors: 22,
    offlineSensors: 2,
    totalSensors: 24,
    alerts: [],
    waterLevelHistory: generateWaterLevelHistory(21, 30),
    lastUpdated: hoursAgo(2),
  },
  {
    id: 'dist-013',
    name: 'Rajkot',
    state: 'Gujarat',
    coordinates: { lat: 22.3039, lng: 70.8022 },
    healthScore: 42,
    riskLevel: 'high',
    trend: 'down',
    rainfall: 610,
    groundwaterDepth: 25.1,
    extractionRate: 8.1,
    rechargeRate: 3.9,
    activeSensors: 14,
    offlineSensors: 1,
    totalSensors: 15,
    alerts: [],
    waterLevelHistory: generateWaterLevelHistory(25, 30),
    lastUpdated: hoursAgo(1),
  },

  // ── CENTRAL & EAST INDIA ────────────────────────────────────────────────────
  {
    id: 'dist-014',
    name: 'Bhopal',
    state: 'Madhya Pradesh',
    coordinates: { lat: 23.2599, lng: 77.4126 },
    healthScore: 59,
    riskLevel: 'moderate',
    trend: 'stable',
    rainfall: 1120,
    groundwaterDepth: 12.8,
    extractionRate: 5.4,
    rechargeRate: 6.2,
    activeSensors: 18,
    offlineSensors: 1,
    totalSensors: 19,
    alerts: [],
    waterLevelHistory: generateWaterLevelHistory(12, 30),
    lastUpdated: hoursAgo(3),
  },
  {
    id: 'dist-015',
    name: 'Indore',
    state: 'Madhya Pradesh',
    coordinates: { lat: 22.7196, lng: 75.8577 },
    healthScore: 45,
    riskLevel: 'high',
    trend: 'down',
    rainfall: 980,
    groundwaterDepth: 19.5,
    extractionRate: 7.8,
    rechargeRate: 4.5,
    activeSensors: 16,
    offlineSensors: 2,
    totalSensors: 18,
    alerts: [],
    waterLevelHistory: generateWaterLevelHistory(19, 30),
    lastUpdated: hoursAgo(2),
  },
  {
    id: 'dist-016',
    name: 'Raipur',
    state: 'Chhattisgarh',
    coordinates: { lat: 21.2514, lng: 81.6296 },
    healthScore: 68,
    riskLevel: 'low',
    trend: 'up',
    rainfall: 1350,
    groundwaterDepth: 10.4,
    extractionRate: 4.6,
    rechargeRate: 7.8,
    activeSensors: 15,
    offlineSensors: 0,
    totalSensors: 15,
    alerts: [],
    waterLevelHistory: generateWaterLevelHistory(10, 30),
    lastUpdated: hoursAgo(4),
  },
  {
    id: 'dist-017',
    name: 'Patna',
    state: 'Bihar',
    coordinates: { lat: 25.5941, lng: 85.1376 },
    healthScore: 62,
    riskLevel: 'moderate',
    trend: 'stable',
    rainfall: 1180,
    groundwaterDepth: 8.9,
    extractionRate: 5.1,
    rechargeRate: 6.9,
    activeSensors: 20,
    offlineSensors: 1,
    totalSensors: 21,
    alerts: [],
    waterLevelHistory: generateWaterLevelHistory(8, 30),
    lastUpdated: hoursAgo(2),
  },
  {
    id: 'dist-018',
    name: 'Ranchi',
    state: 'Jharkhand',
    coordinates: { lat: 23.3441, lng: 85.3096 },
    healthScore: 55,
    riskLevel: 'moderate',
    trend: 'stable',
    rainfall: 1400,
    groundwaterDepth: 11.2,
    extractionRate: 4.8,
    rechargeRate: 5.9,
    activeSensors: 14,
    offlineSensors: 1,
    totalSensors: 15,
    alerts: [],
    waterLevelHistory: generateWaterLevelHistory(11, 30),
    lastUpdated: hoursAgo(3),
  },
  {
    id: 'dist-019',
    name: 'Kolkata',
    state: 'West Bengal',
    coordinates: { lat: 22.5726, lng: 88.3639 },
    healthScore: 65,
    riskLevel: 'low',
    trend: 'stable',
    rainfall: 1620,
    groundwaterDepth: 7.8,
    extractionRate: 4.2,
    rechargeRate: 7.9,
    activeSensors: 24,
    offlineSensors: 1,
    totalSensors: 25,
    alerts: [],
    waterLevelHistory: generateWaterLevelHistory(7, 30),
    lastUpdated: hoursAgo(1),
  },
  {
    id: 'dist-020',
    name: 'Bhubaneswar',
    state: 'Odisha',
    coordinates: { lat: 20.2961, lng: 85.8245 },
    healthScore: 71,
    riskLevel: 'low',
    trend: 'up',
    rainfall: 1540,
    groundwaterDepth: 6.4,
    extractionRate: 3.8,
    rechargeRate: 8.2,
    activeSensors: 19,
    offlineSensors: 0,
    totalSensors: 19,
    alerts: [],
    waterLevelHistory: generateWaterLevelHistory(6, 30),
    lastUpdated: hoursAgo(2),
  },

  // ── SOUTH INDIA ─────────────────────────────────────────────────────────────
  {
    id: 'dist-021',
    name: 'Bengaluru',
    state: 'Karnataka',
    coordinates: { lat: 12.9716, lng: 77.5946 },
    healthScore: 33,
    riskLevel: 'critical',
    trend: 'down',
    rainfall: 920,
    groundwaterDepth: 36.8,
    extractionRate: 13.1,
    rechargeRate: 2.9,
    activeSensors: 30,
    offlineSensors: 4,
    totalSensors: 34,
    alerts: [],
    waterLevelHistory: generateWaterLevelHistory(36, 30),
    lastUpdated: hoursAgo(0.5),
  },
  {
    id: 'dist-022',
    name: 'Hyderabad',
    state: 'Telangana',
    coordinates: { lat: 17.3850, lng: 78.4867 },
    healthScore: 46,
    riskLevel: 'moderate',
    trend: 'stable',
    rainfall: 810,
    groundwaterDepth: 17.2,
    extractionRate: 6.8,
    rechargeRate: 5.1,
    activeSensors: 26,
    offlineSensors: 2,
    totalSensors: 28,
    alerts: [],
    waterLevelHistory: generateWaterLevelHistory(17, 30),
    lastUpdated: hoursAgo(1),
  },
  {
    id: 'dist-023',
    name: 'Warangal',
    state: 'Telangana',
    coordinates: { lat: 17.9689, lng: 79.5941 },
    healthScore: 78,
    riskLevel: 'low',
    trend: 'up',
    rainfall: 980,
    groundwaterDepth: 9.8,
    extractionRate: 3.1,
    rechargeRate: 8.2,
    activeSensors: 11,
    offlineSensors: 0,
    totalSensors: 11,
    alerts: [],
    waterLevelHistory: generateWaterLevelHistory(9, 30),
    lastUpdated: hoursAgo(2),
  },
  {
    id: 'dist-024',
    name: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    coordinates: { lat: 17.6868, lng: 83.2185 },
    healthScore: 61,
    riskLevel: 'moderate',
    trend: 'stable',
    rainfall: 1100,
    groundwaterDepth: 11.4,
    extractionRate: 5.2,
    rechargeRate: 6.5,
    activeSensors: 17,
    offlineSensors: 1,
    totalSensors: 18,
    alerts: [],
    waterLevelHistory: generateWaterLevelHistory(11, 30),
    lastUpdated: hoursAgo(3),
  },
  {
    id: 'dist-025',
    name: 'Anantapur',
    state: 'Andhra Pradesh',
    coordinates: { lat: 14.6819, lng: 77.6006 },
    healthScore: 29,
    riskLevel: 'critical',
    trend: 'down',
    rainfall: 520,
    groundwaterDepth: 42.1,
    extractionRate: 10.4,
    rechargeRate: 1.8,
    activeSensors: 12,
    offlineSensors: 3,
    totalSensors: 15,
    alerts: [],
    waterLevelHistory: generateWaterLevelHistory(42, 30),
    lastUpdated: hoursAgo(1),
  },
  {
    id: 'dist-026',
    name: 'Chennai',
    state: 'Tamil Nadu',
    coordinates: { lat: 13.0827, lng: 80.2707 },
    healthScore: 37,
    riskLevel: 'high',
    trend: 'down',
    rainfall: 1400,
    groundwaterDepth: 24.8,
    extractionRate: 11.8,
    rechargeRate: 3.8,
    activeSensors: 25,
    offlineSensors: 3,
    totalSensors: 28,
    alerts: [],
    waterLevelHistory: generateWaterLevelHistory(24, 30),
    lastUpdated: hoursAgo(0.5),
  },
  {
    id: 'dist-027',
    name: 'Coimbatore',
    state: 'Tamil Nadu',
    coordinates: { lat: 11.0168, lng: 76.9558 },
    healthScore: 76,
    riskLevel: 'low',
    trend: 'up',
    rainfall: 680,
    groundwaterDepth: 11.2,
    extractionRate: 3.4,
    rechargeRate: 7.8,
    activeSensors: 14,
    offlineSensors: 0,
    totalSensors: 14,
    alerts: [],
    waterLevelHistory: generateWaterLevelHistory(11, 30),
    lastUpdated: hoursAgo(1),
  },
  {
    id: 'dist-028',
    name: 'Thiruvananthapuram',
    state: 'Kerala',
    coordinates: { lat: 8.5241, lng: 76.9366 },
    healthScore: 82,
    riskLevel: 'low',
    trend: 'up',
    rainfall: 1820,
    groundwaterDepth: 5.6,
    extractionRate: 2.8,
    rechargeRate: 9.4,
    activeSensors: 16,
    offlineSensors: 0,
    totalSensors: 16,
    alerts: [],
    waterLevelHistory: generateWaterLevelHistory(5, 30),
    lastUpdated: hoursAgo(2),
  },

  // ── WEST COAST & MAHARASHTRA ────────────────────────────────────────────────
  {
    id: 'dist-029',
    name: 'Mumbai',
    state: 'Maharashtra',
    coordinates: { lat: 19.0760, lng: 72.8777 },
    healthScore: 64,
    riskLevel: 'low',
    trend: 'stable',
    rainfall: 2200,
    groundwaterDepth: 8.2,
    extractionRate: 4.8,
    rechargeRate: 7.4,
    activeSensors: 28,
    offlineSensors: 2,
    totalSensors: 30,
    alerts: [],
    waterLevelHistory: generateWaterLevelHistory(8, 30),
    lastUpdated: hoursAgo(1),
  },
  {
    id: 'dist-030',
    name: 'Pune',
    state: 'Maharashtra',
    coordinates: { lat: 18.5204, lng: 73.8567 },
    healthScore: 58,
    riskLevel: 'moderate',
    trend: 'stable',
    rainfall: 890,
    groundwaterDepth: 13.4,
    extractionRate: 5.9,
    rechargeRate: 5.8,
    activeSensors: 24,
    offlineSensors: 1,
    totalSensors: 25,
    alerts: [],
    waterLevelHistory: generateWaterLevelHistory(13, 30),
    lastUpdated: hoursAgo(2),
  },
  {
    id: 'dist-031',
    name: 'Nashik',
    state: 'Maharashtra',
    coordinates: { lat: 19.9975, lng: 73.7898 },
    healthScore: 54,
    riskLevel: 'moderate',
    trend: 'stable',
    rainfall: 690,
    groundwaterDepth: 14.6,
    extractionRate: 6.2,
    rechargeRate: 5.8,
    activeSensors: 21,
    offlineSensors: 2,
    totalSensors: 23,
    alerts: [],
    waterLevelHistory: generateWaterLevelHistory(14, 30),
    lastUpdated: hoursAgo(1),
  },
  {
    id: 'dist-032',
    name: 'Latur',
    state: 'Maharashtra',
    coordinates: { lat: 18.4088, lng: 76.5604 },
    healthScore: 26,
    riskLevel: 'critical',
    trend: 'down',
    rainfall: 610,
    groundwaterDepth: 39.4,
    extractionRate: 10.9,
    rechargeRate: 1.9,
    activeSensors: 12,
    offlineSensors: 3,
    totalSensors: 15,
    alerts: [],
    waterLevelHistory: generateWaterLevelHistory(39, 30),
    lastUpdated: hoursAgo(1),
  },
  {
    id: 'dist-033',
    name: 'Panaji',
    state: 'Goa',
    coordinates: { lat: 15.4909, lng: 73.8278 },
    healthScore: 84,
    riskLevel: 'low',
    trend: 'up',
    rainfall: 2900,
    groundwaterDepth: 4.8,
    extractionRate: 2.1,
    rechargeRate: 9.8,
    activeSensors: 10,
    offlineSensors: 0,
    totalSensors: 10,
    alerts: [],
    waterLevelHistory: generateWaterLevelHistory(4, 30),
    lastUpdated: hoursAgo(4),
  },

  // ── NORTH EAST INDIA ────────────────────────────────────────────────────────
  {
    id: 'dist-034',
    name: 'Guwahati',
    state: 'Assam',
    coordinates: { lat: 26.1445, lng: 91.7362 },
    healthScore: 81,
    riskLevel: 'low',
    trend: 'up',
    rainfall: 1720,
    groundwaterDepth: 6.8,
    extractionRate: 2.9,
    rechargeRate: 8.8,
    activeSensors: 13,
    offlineSensors: 0,
    totalSensors: 13,
    alerts: [],
    waterLevelHistory: generateWaterLevelHistory(6, 30),
    lastUpdated: hoursAgo(2),
  },
  {
    id: 'dist-035',
    name: 'Shillong',
    state: 'Meghalaya',
    coordinates: { lat: 25.5788, lng: 91.8933 },
    healthScore: 88,
    riskLevel: 'low',
    trend: 'up',
    rainfall: 2400,
    groundwaterDepth: 3.9,
    extractionRate: 1.8,
    rechargeRate: 9.9,
    activeSensors: 8,
    offlineSensors: 0,
    totalSensors: 8,
    alerts: [],
    waterLevelHistory: generateWaterLevelHistory(3, 30),
    lastUpdated: hoursAgo(5),
  },
  {
    id: 'dist-036',
    name: 'Imphal',
    state: 'Manipur',
    coordinates: { lat: 24.8170, lng: 93.9368 },
    healthScore: 75,
    riskLevel: 'low',
    trend: 'stable',
    rainfall: 1450,
    groundwaterDepth: 7.2,
    extractionRate: 3.2,
    rechargeRate: 7.6,
    activeSensors: 9,
    offlineSensors: 0,
    totalSensors: 9,
    alerts: [],
    waterLevelHistory: generateWaterLevelHistory(7, 30),
    lastUpdated: hoursAgo(3),
  },
  {
    id: 'dist-037',
    name: 'Agartala',
    state: 'Tripura',
    coordinates: { lat: 23.8315, lng: 91.2868 },
    healthScore: 79,
    riskLevel: 'low',
    trend: 'up',
    rainfall: 1890,
    groundwaterDepth: 5.9,
    extractionRate: 2.6,
    rechargeRate: 8.5,
    activeSensors: 10,
    offlineSensors: 0,
    totalSensors: 10,
    alerts: [],
    waterLevelHistory: generateWaterLevelHistory(5, 30),
    lastUpdated: hoursAgo(4),
  }
];

// ── Alerts ────────────────────────────────────────────────────────────────────

export const MOCK_ALERTS: Alert[] = [
  {
    id: 'alert-001',
    districtId: 'dist-001',
    districtName: 'Jhansi',
    state: 'Uttar Pradesh',
    severity: 'critical',
    type: 'Rapid Depletion',
    message: 'Groundwater level dropped 2.4m in last 30 days. Immediate intervention required.',
    timestamp: hoursAgo(2),
    acknowledged: false,
  },
  {
    id: 'alert-002',
    districtId: 'dist-002',
    districtName: 'Bikaner',
    state: 'Rajasthan',
    severity: 'critical',
    type: 'Critical Threshold',
    message: 'Water table has crossed the critical threshold of 55m BGL.',
    timestamp: hoursAgo(4),
    acknowledged: false,
  },
  {
    id: 'alert-003',
    districtId: 'dist-004',
    districtName: 'Ludhiana',
    state: 'Punjab',
    severity: 'warning',
    type: 'Over-extraction',
    message: 'Extraction rate 3x higher than recharge. Seasonal regulation advised.',
    timestamp: hoursAgo(6),
    acknowledged: false,
  },
  {
    id: 'alert-004',
    districtId: 'dist-011',
    districtName: 'Hisar',
    state: 'Haryana',
    severity: 'critical',
    type: 'Sensor Offline',
    message: '4 DWLR sensors offline. Coverage gap in northern zone.',
    timestamp: hoursAgo(8),
    acknowledged: true,
  },
  {
    id: 'alert-005',
    districtId: 'dist-012',
    districtName: 'Anantapur',
    state: 'Andhra Pradesh',
    severity: 'warning',
    type: 'Declining Trend',
    message: 'Consistent 6-month declining trend observed. Prediction model flagged high risk.',
    timestamp: hoursAgo(12),
    acknowledged: false,
  },
  {
    id: 'alert-006',
    districtId: 'dist-003',
    districtName: 'Jodhpur',
    state: 'Rajasthan',
    severity: 'critical',
    type: 'Monsoon Deficit',
    message: 'Below-average monsoon (-42%) will worsen existing depletion.',
    timestamp: hoursAgo(18),
    acknowledged: false,
  },
  {
    id: 'alert-007',
    districtId: 'dist-006',
    districtName: 'Nashik',
    state: 'Maharashtra',
    severity: 'info',
    type: 'Recharge Improvement',
    message: 'MAR (Managed Aquifer Recharge) programme showing positive results.',
    timestamp: daysAgo(1),
    acknowledged: true,
  },
];

// Attach alerts to districts
MOCK_DISTRICTS.forEach(d => {
  d.alerts = MOCK_ALERTS.filter(a => a.districtId === d.id);
});

// ── Sensors ───────────────────────────────────────────────────────────────────
export const MOCK_SENSORS: Sensor[] = MOCK_DISTRICTS.flatMap(d =>
  Array.from({ length: d.totalSensors }, (_, i) => ({
    id: `sensor-${d.id}-${i + 1}`,
    name: `DWLR-${d.name.substring(0, 3).toUpperCase()}-${String(i + 1).padStart(3, '0')}`,
    districtId: d.id,
    coordinates: {
      lat: d.coordinates.lat + (Math.random() - 0.5) * 0.5,
      lng: d.coordinates.lng + (Math.random() - 0.5) * 0.5,
    },
    status: i < d.offlineSensors ? 'offline' : i === d.offlineSensors ? 'warning' : 'online',
    lastReading: d.groundwaterDepth + (Math.random() - 0.5) * 2,
    lastUpdated: hoursAgo(Math.floor(Math.random() * 6)),
    batteryLevel: i < d.offlineSensors ? 0 : Math.floor(Math.random() * 40 + 60),
    signalStrength: i < d.offlineSensors ? 0 : Math.floor(Math.random() * 30 + 70),
    installDate: daysAgo(Math.floor(Math.random() * 365 + 180)),
  }))
);

// ── Predictions ───────────────────────────────────────────────────────────────
export const MOCK_PREDICTIONS: Prediction[] = [
  {
    id: 'pred-001',
    districtId: 'dist-001',
    districtName: 'Jhansi',
    state: 'Uttar Pradesh',
    horizon: '6month',
    confidenceScore: 87,
    predictedRisk: 'critical',
    trend: 'down',
    data: Array.from({ length: 6 }, (_, i) => ({
      timestamp: new Date(Date.now() + i * 30 * 24 * 60 * 60 * 1000).toISOString(),
      predicted: 34.2 + i * 1.8,
      confidenceLow: 34.2 + i * 1.2,
      confidenceHigh: 34.2 + i * 2.4,
    })),
    generatedAt: hoursAgo(6),
    modelVersion: 'AquaPredict-v2.1 [PLACEHOLDER]',
  },
  {
    id: 'pred-002',
    districtId: 'dist-004',
    districtName: 'Ludhiana',
    state: 'Punjab',
    horizon: '1year',
    confidenceScore: 79,
    predictedRisk: 'critical',
    trend: 'down',
    data: Array.from({ length: 12 }, (_, i) => ({
      timestamp: new Date(Date.now() + i * 30 * 24 * 60 * 60 * 1000).toISOString(),
      predicted: 28.4 + i * 2.1,
      confidenceLow: 28.4 + i * 1.4,
      confidenceHigh: 28.4 + i * 2.8,
    })),
    generatedAt: hoursAgo(12),
    modelVersion: 'AquaPredict-v2.1 [PLACEHOLDER]',
  },
  {
    id: 'pred-003',
    districtId: 'dist-007',
    districtName: 'Warangal',
    state: 'Telangana',
    horizon: '3month',
    confidenceScore: 91,
    predictedRisk: 'low',
    trend: 'up',
    data: Array.from({ length: 3 }, (_, i) => ({
      timestamp: new Date(Date.now() + i * 30 * 24 * 60 * 60 * 1000).toISOString(),
      predicted: 9.8 - i * 0.4,
      confidenceLow: 9.8 - i * 0.6,
      confidenceHigh: 9.8 - i * 0.2,
    })),
    generatedAt: hoursAgo(3),
    modelVersion: 'AquaPredict-v2.1 [PLACEHOLDER]',
  },
];

// ── AI Recommendations (Placeholders) ────────────────────────────────────────
export const MOCK_RECOMMENDATIONS: AIRecommendation[] = [
  {
    id: 'rec-001',
    districtId: 'dist-001',
    districtName: 'Jhansi',
    priority: 'urgent',
    summary: 'Implement immediate groundwater extraction moratorium',
    details: 'Based on 6-month depletion trend analysis, groundwater levels in Jhansi are projected to cross the irreversible depletion threshold by Q3. Recommend: (1) Temporary ban on agricultural tube-wells, (2) Deploy 3 new artificial recharge sites, (3) Issue district-level water emergency advisory.',
    confidence: 87,
    generatedAt: hoursAgo(4),
  },
  {
    id: 'rec-002',
    districtId: 'dist-002',
    districtName: 'Bikaner',
    priority: 'urgent',
    summary: 'Emergency water supply augmentation required',
    details: 'Bikaner district has entered critical scarcity zone. Recommend: (1) Expedite Indira Gandhi Canal diversion, (2) Deploy 5 tanker supply routes for drinking water priority, (3) Activate Rajasthan State Emergency Water Protocol.',
    confidence: 92,
    generatedAt: hoursAgo(6),
  },
  {
    id: 'rec-003',
    districtId: 'dist-004',
    districtName: 'Ludhiana',
    priority: 'high',
    summary: 'Crop pattern intervention advisory',
    details: 'Punjab paddy cultivation is the primary driver of over-extraction. Recommend: (1) Promote shift to less water-intensive crops (maize, pulses), (2) Implement paddy transplantation delay by 15 days, (3) Provide financial incentives for drip irrigation adoption.',
    confidence: 78,
    generatedAt: hoursAgo(8),
  },
];

// ── Decision Records ──────────────────────────────────────────────────────────
export const MOCK_DECISIONS: DecisionRecord[] = [
  {
    id: 'dec-001',
    recommendationId: 'rec-003',
    districtName: 'Ludhiana',
    status: 'approved',
    officerName: 'Dr. Rajesh Kumar, IAS',
    note: 'Approved for FY 2025-26 Rabi season. MoU with Punjab Agriculture Dept initiated.',
    timestamp: daysAgo(2),
  },
  {
    id: 'dec-002',
    recommendationId: 'rec-001',
    districtName: 'Jhansi',
    status: 'modified',
    officerName: 'Smt. Priya Sharma, IAS',
    note: 'Moratorium scope reduced to commercial extraction only. Domestic use exempted.',
    timestamp: daysAgo(5),
  },
  {
    id: 'dec-003',
    recommendationId: 'rec-002',
    districtName: 'Bikaner',
    status: 'pending',
    officerName: 'Pending Review',
    note: '',
    timestamp: hoursAgo(4),
  },
];

// ── Reports ───────────────────────────────────────────────────────────────────
export const MOCK_REPORTS: Report[] = [
  {
    id: 'rep-001',
    title: 'National Groundwater Status Report — June 2025',
    type: 'monthly',
    period: 'June 2025',
    generatedAt: daysAgo(2),
    generatedBy: 'System',
    fileSize: '4.2 MB',
    pages: 48,
    status: 'ready',
  },
  {
    id: 'rep-002',
    title: 'Critical Districts — Emergency Assessment Q2 2025',
    type: 'quarterly',
    district: 'Multiple',
    period: 'Q2 2025',
    generatedAt: daysAgo(7),
    generatedBy: 'Dr. Anand Verma',
    fileSize: '8.7 MB',
    pages: 102,
    status: 'ready',
  },
  {
    id: 'rep-003',
    title: 'Annual Groundwater Survey Report 2024-25',
    type: 'annual',
    period: 'FY 2024-25',
    generatedAt: daysAgo(30),
    generatedBy: 'System',
    fileSize: '22.1 MB',
    pages: 284,
    status: 'ready',
  },
  {
    id: 'rep-004',
    title: 'Rajasthan Drought Risk Analysis — July 2025',
    type: 'custom',
    state: 'Rajasthan',
    period: 'July 2025',
    generatedAt: hoursAgo(12),
    generatedBy: 'Smt. Kavita Mehta',
    fileSize: '3.1 MB',
    pages: 34,
    status: 'ready',
  },
  {
    id: 'rep-005',
    title: 'Punjab Over-Extraction Alert Report',
    type: 'alert',
    state: 'Punjab',
    period: 'July 2025',
    generatedAt: hoursAgo(6),
    generatedBy: 'System',
    fileSize: '1.8 MB',
    pages: 18,
    status: 'generating',
  },
];

// ── Users ─────────────────────────────────────────────────────────────────────
export const MOCK_USERS: User[] = [
  {
    id: 'usr-001',
    name: 'Dr. Anand Verma',
    email: 'anand.verma@cgwb.gov.in',
    role: 'admin',
    department: 'Central Ground Water Board',
    status: 'active',
    lastActive: hoursAgo(0.5),
  },
  {
    id: 'usr-002',
    name: 'Smt. Priya Sharma',
    email: 'priya.sharma@up.gov.in',
    role: 'officer',
    department: 'State Ground Water Authority',
    state: 'Uttar Pradesh',
    status: 'active',
    lastActive: hoursAgo(1),
  },
  {
    id: 'usr-003',
    name: 'Rajesh Kumar',
    email: 'rajesh.kumar@punjab.gov.in',
    role: 'officer',
    department: 'Punjab Water Resources',
    state: 'Punjab',
    status: 'active',
    lastActive: hoursAgo(3),
  },
  {
    id: 'usr-004',
    name: 'Dr. Meera Iyer',
    email: 'meera.iyer@cgwb.gov.in',
    role: 'analyst',
    department: 'Central Ground Water Board',
    status: 'active',
    lastActive: daysAgo(1),
  },
  {
    id: 'usr-005',
    name: 'Smt. Kavita Mehta',
    email: 'kavita.mehta@rajasthan.gov.in',
    role: 'analyst',
    department: 'Rajasthan Ground Water Department',
    state: 'Rajasthan',
    status: 'active',
    lastActive: hoursAgo(6),
  },
  {
    id: 'usr-006',
    name: 'Arjun Nair',
    email: 'arjun.nair@kerala.gov.in',
    role: 'viewer',
    department: 'Kerala Water Authority',
    state: 'Kerala',
    status: 'active',
    lastActive: daysAgo(2),
  },
  {
    id: 'usr-007',
    name: 'Suresh Reddy',
    email: 'suresh.reddy@telangana.gov.in',
    role: 'viewer',
    department: 'Telangana Ground Water Department',
    state: 'Telangana',
    status: 'inactive',
    lastActive: daysAgo(14),
  },
];

// ── Dashboard Statistics ───────────────────────────────────────────────────────
export const DASHBOARD_STATS = {
  nationalHealthScore: 58,
  groundwaterSustainability: 62,
  activeSensors: MOCK_SENSORS.filter(s => s.status === 'online').length,
  totalSensors: MOCK_SENSORS.length,
  offlineSensors: MOCK_SENSORS.filter(s => s.status === 'offline').length,
  criticalDistricts: MOCK_DISTRICTS.filter(d => d.riskLevel === 'critical').length,
  highRiskAreas: MOCK_DISTRICTS.filter(d => d.riskLevel === 'high').length,
  todayAlerts: MOCK_ALERTS.filter(a => !a.acknowledged).length,
};

// ── Monthly Chart Data ─────────────────────────────────────────────────────────
export const MONTHLY_WATER_LEVEL_DATA = {
  labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
  depth: [18.2, 19.1, 20.4, 22.1, 23.8, 24.2, 20.1, 16.4, 14.2, 15.1, 16.8, 17.9],
  extraction: [8.2, 7.8, 9.1, 10.4, 11.2, 10.8, 7.4, 5.8, 6.2, 7.1, 8.0, 8.4],
  recharge: [2.1, 1.8, 1.4, 0.9, 0.7, 2.8, 6.4, 8.2, 7.1, 4.2, 2.8, 2.1],
  rainfall: [12, 8, 4, 2, 1, 42, 145, 182, 124, 58, 18, 10],
};

export const YEARLY_WATER_LEVEL_DATA = {
  labels: ['2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025'],
  depth: [14.2, 15.8, 16.4, 17.1, 18.8, 20.2, 21.4, 22.8],
  extraction: [7.2, 7.8, 8.1, 8.4, 8.9, 9.2, 9.8, 10.1],
  recharge: [4.8, 4.2, 3.9, 3.6, 3.2, 2.8, 2.4, 2.1],
};

// ── GIS Map Overlays Mock Data ────────────────────────────────────────────────
export const MOCK_VILLAGES = MOCK_DISTRICTS.flatMap(d => [
  {
    id: `vil-${d.id}-1`,
    name: `${d.name} Basin North`,
    districtId: d.id,
    state: d.state,
    coordinates: { lat: d.coordinates.lat + 0.08, lng: d.coordinates.lng + 0.06 },
    riskLevel: d.riskLevel,
    healthScore: Math.min(100, d.healthScore + 4),
  },
  {
    id: `vil-${d.id}-2`,
    name: `${d.name} Sector South`,
    districtId: d.id,
    state: d.state,
    coordinates: { lat: d.coordinates.lat - 0.07, lng: d.coordinates.lng - 0.08 },
    riskLevel: d.riskLevel === 'critical' ? 'high' : d.riskLevel,
    healthScore: Math.max(0, d.healthScore - 8),
  },
  {
    id: `vil-${d.id}-3`,
    name: `${d.name} Station West`,
    districtId: d.id,
    state: d.state,
    coordinates: { lat: d.coordinates.lat + 0.05, lng: d.coordinates.lng - 0.07 },
    riskLevel: d.riskLevel,
    healthScore: d.healthScore,
  }
]);

export const MOCK_RIVERS = [
  // Betwa River near Jhansi coordinates
  {
    name: 'Betwa River',
    path: [
      [24.5, 78.2],
      [25.0, 78.4],
      [25.4484, 78.5685],
      [25.9, 78.8],
      [26.2, 79.2]
    ] as [number, number][]
  },
  // Chambal River flowing in Rajasthan
  {
    name: 'Chambal River',
    path: [
      [25.0, 75.5],
      [25.8, 76.2],
      [26.2389, 77.0243],
      [26.8, 77.8],
      [27.1, 78.5]
    ] as [number, number][]
  },
  // Sutlej River near Ludhiana
  {
    name: 'Sutlej River',
    path: [
      [31.2, 75.0],
      [30.901, 75.8573],
      [31.1, 76.4],
      [31.3, 77.2]
    ] as [number, number][]
  }
];

export const MOCK_CANALS = [
  // Indira Gandhi Canal near Bikaner coordinates
  {
    name: 'Indira Gandhi Canal Main branch',
    path: [
      [29.2, 73.8],
      [28.5, 73.5],
      [28.0229, 73.3119],
      [27.4, 72.8],
      [26.8, 72.2]
    ] as [number, number][]
  },
  // Ganga Canal Branch near Jhansi
  {
    name: 'Ganga Canal Branch III',
    path: [
      [26.1, 78.4],
      [25.7, 78.5],
      [25.4484, 78.5685],
      [25.1, 78.7]
    ] as [number, number][]
  }
];

export const MOCK_RESERVOIRS = [
  {
    name: 'Jhansi Aquifer Reservoir',
    polygon: [
      [25.50, 78.60],
      [25.52, 78.62],
      [25.51, 78.65],
      [25.48, 78.64],
      [25.47, 78.61]
    ] as [number, number][]
  },
  {
    name: 'Bikaner Dry Reservoir Basin',
    polygon: [
      [28.05, 73.35],
      [28.08, 73.37],
      [28.07, 73.40],
      [28.03, 73.39],
      [28.02, 73.36]
    ] as [number, number][]
  }
];

